### ISSUE TITLE
https://github.com/lestrrat-go/libxml2/blob/master/clib/clib.go Package Build is failing with  "could not determine kind of name for C.free"

### ISSUE THREAD

**Issue by Priyankasoni037** [lestrrat-go/libxml2#101]
This happens after the last change has been made for this repo. 
https://github.com/lestrrat-go/libxml2/commit/b65cd51053703d2b0eb6992c8a815430474578ed

Before that it was working as expected

**Describe the bug**
While downloading the below package
https://github.com/lestrrat-go/libxml2/blob/master/clib/clib.go
Getting the Error message as **"could not determine kind of name for C.free"**
![336443708-bd21517a-19c2-4145-8c1e-8d416fb93113](https://github.com/lestrrat-go/libxml2/assets/55648788/e69fb595-c0fe-4340-8241-c513e8b74c34)

**To Reproduce / Expected behavior**

**Comment by lestrrat** [comment]
I can't reproduce it. Just a guess but perhaps you are using an old Go version?

**Comment by Priyankasoni037** [comment]
It fails with the same error with the latest GO version as well Go 1.22.4
![image (4)](https://github.com/lestrrat-go/libxml2/assets/55648788/e5563cc0-72ca-4630-93f4-2e8da9e90944)

**Comment by lestrrat** [comment]
Bummer. But I since I can't reproduce it, I can't do much. Please provide a reproducible scenario.

**Comment by nobuenhombre** [comment]
> This happens after the last change has been made for this repo. [b65cd51](https://github.com/lestrrat-go/libxml2/commit/b65cd51053703d2b0eb6992c8a815430474578ed)
> 
> Before that it was working as expected
> 
> **Describe the bug** While downloading the below package https://github.com/lestrrat-go/libxml2/blob/master/clib/clib.go Getting the Error message as **"could not determine kind of name for C.free"** ![336443708-bd21517a-19c2-4145-8c1e-8d416fb93113](https://private-user-images.githubusercontent.com/55648788/336698358-e69fb595-c0fe-4340-8241-c513e8b74c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzA2OTUsIm5iZiI6MTcxODYzMDM5NSwicGF0aCI6Ii81NTY0ODc4OC8zMzY2OTgzNTgtZTY5ZmI1OTUtYzBmZS00MzQwLTgyNDEtYzUxM2U4Yjc0YzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzMTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzJlNDk3NDliZGJlNTVjOGI3ZWJlMjdmOTQ3M2Y5YWIxMDBmNDEzZDM1OGFjM2RkMTkxMzc2ZmVmZDM5MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23pNjDzPzPSPvY-dIuUTSysYrp4D1fcL3DX-bw7N2l4)
> 
> **To Reproduce / Expected behavior**

I also have a similar problem

How did I solve it?

1. Install required system packages
for Ubuntu
`sudo apt install icu-devtools libicu-dev`

for Docker
`FROM golang:alpine as builder

RUN apk update && apk add --update --no-cache \
    ca-certificates \
    gcc \
    musl-dev \
    libxml2 \
    libxml2-dev \
    icu \
    icu-dev`

2. In command to build executable add special flag
`CGO_CFLAGS="-I/usr/include/unicode"`

That's all

**Comment by Priyankasoni037** [comment]
Still, we are facing the same issue  :(

 /go/pkg/mod/github.com/lestrrat/go-libxml2@v0.0.0-20180221004755-bb78334e2019/clib/clib.go:489:8: could not determine kind of name for C.free

**Comment by lestrrat** [comment]
@Priyankasoni037 as I already said, you need to isolate what it is that differs from the CI environment that produces your error. Otherwise I will never be able to do anything on this.
