### ISSUE TITLE
How to compile with CGO_ENABLED=0 flag?

### ISSUE THREAD

**Issue by dtelyukh** [lestrrat-go/libxml2#33]
$CGO_ENABLED=0 GOOS=linux go build

../../vendor/github.com/lestrrat/go-libxml2/xpath/xpath.go:40: undefined: clib.XMLXPathObjectType
../../vendor/github.com/lestrrat/go-libxml2/xpath/xpath.go:45: undefined: clib.XMLXPathObjectFloat64
../../vendor/github.com/lestrrat/go-libxml2/xpath/xpath.go:50: undefined: clib.XMLXPathObjectBool
...

CGO_ENABLED=0 needed for building alpine-based docker container.

Is there any solution?

**Comment by lestrrat** [comment]
I haven't tried it, but there's some mention of CC_FOR_TARGET and CC at https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command

**Comment by dtelyukh** [comment]
Is it possible to implement the same solution https://github.com/shadowmint/go-static-linking?

**Comment by lestrrat** [comment]
no idea :/

**Comment by hulet** [comment]
To answer your original question you can't compile this library with CGO_ENABLED=0; `libxml2` uses the "C" pseudo-package and needs a C compiler to compile the C code.

See the paragraphs on cross-compiling at https://golang.org/cmd/cgo/ and the explanation at https://github.com/golang/go/issues/12888#issuecomment-146880368.

You can install a cross-compiler, skip cross-compiling and just build on the native platform, or use a tool like https://github.com/karalabe/xgo. Good luck!
