### ISSUE TITLE
Problem with using Find method on Node

### ISSUE THREAD

**Issue by kLkA** [lestrrat-go/libxml2#41]
Hello, I have following situation.
Here you can see working example:
1) Getting successfully parsed document
2) Extracting list of nodes by xpath expression
3) Parsing string of ODNode into new document and getting nodes by `Find` method.

```go
DocumentPtr := *DocumentPtrRaw.(*types.Document)
odNodes := xpath.NodeList(DocumentPtr.Find("//*[local-name()='OriginDestination']"))

for _, ODNode := range odNodes {
    // Didn't succeed to use find on main document pointer so parsed xml part again. Very strange error
    doc, _ := libxml2.ParseString(ODNode.String())
    nodes := xpath.NodeList(doc.Find("./*/AirportCode"))
    codes := []string{}
    for _, airportCodeNode := range nodes {
        codes = append(codes, airportCodeNode.NodeValue())
    }
    ODList = append(ODList, codes)
}
```

Before it I tried to use `ODNode.Find("./*/AirportCode")` statement but it doesn't work. Could you help me get idea why it's not working? I found that inside both .Find methods finally use same `Node.Find` method.. but `ODNode.Find` didn't work in any ways except `ODNode.Find(".")`

Is it bug or I'm doing something wrong?

**Comment by lestrrat** [comment]
@kLkA sorry for not replying. Can you please provide a complete code (preferably in go test format) that reproduces this?
