### ISSUE TITLE
Capturing parser errors programmatically

### ISSUE THREAD

**Issue by the4thamigo-uk** [lestrrat-go/libxml2#52]
Hi,

I can currently see detailed errors generated by libxml in stdout, but I need to suppress this output and capture the errors programmatically. Is there a way to do this at present?

e.g. I want to capture error detail such as the following in the `error` object returning from `Parse` :

```
Entity: line 1: parser error : Start tag expected, '<' not found
invalid
^
```

**Comment by lestrrat** [comment]
That's one of those things I was never able to fully grasp from reading the libxml2 source. I suspect I should be using xmlParserError in xmlerror.h, but it takes a "format", and I'm just not sure how to properly use it.

**Comment by the4thamigo-uk** [comment]
At a minimum you could support `xmlGetLastError`. It is thread-specific however so not sure how this would work with multiple go routines.

**Comment by the4thamigo-uk** [comment]
In fact http://www.xmlsoft.org/html/libxml-xmlerror.html#xmlCtxtGetLastError is probably more appropriate here

**Comment by the4thamigo-uk** [comment]
Can you use `xmlGetLastError`

**Comment by lestrrat** [comment]
Well, with `xmlXXXGetLastError` you will get the struct back, but don't you need to format it?
Ah well, if you can come up with a PR, that's dandy either way :)

**Comment by the4thamigo-uk** [comment]
Seems to work, but it misses some of the error context e.g. the following :+1: 

```
Entity: line 1: parser error : Start tag expected, '<' not found
invalid
^
```

Is captured as : 

```
Start tag expected, '<' not found
```

But it is a start at least

**Comment by lestrrat** [comment]
Right, the struct has separate fields for file names and line numbers. Also, as I wrote in the PR, I think you may need to think about releasing the error struct?

**Comment by the4thamigo-uk** [comment]
yeah I just saw that after reading your last comment : 

```
Structure xmlError
struct _xmlError {
    int	domain	: What part of the library raised this er
    int	code	: The error code, e.g. an xmlParserError
    char *	message	: human-readable informative error messag
    xmlErrorLevel	level	: how consequent is the error
    char *	file	: the filename
    int	line	: the line number if available
    char *	str1	: extra string information
    char *	str2	: extra string information
    char *	str3	: extra string information
    int	int1	: extra number information
    int	int2	: error column # or 0 if N/A (todo: renam
    void *	ctxt	: the parser context if available
    void *	node	: the node in the tree
}
```
