### ISSUE TITLE
'Failed to document' error message is not very meaningful

### ISSUE THREAD

**Issue by the4thamigo-uk** [lestrrat-go/libxml2#54]
The error message 'failed to document' in the existing code doesnt mean a lot to me. How are you meant to interpret that as a user of the library?

https://github.com/lestrrat-go/libxml2/blob/master/clib/clib.go#L2203

**Comment by lestrrat** [comment]
Man, I've been bad by warnocking this. The error message is changed, but if it didn't give you any more context than that already, then libxml2 didn't really give us any more errors. Either I'm looking at the wrong place, or libxml2 (or the version you have) didn't report it.

Failing test cases welcome.
