### ISSUE TITLE
disable Ctrl+C

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [lestrrat-go/libxml2#55]
Without errors. This, only deactivate "Ctrl + C" in the console and I must close the console and open the console, and restart the server and "this is very tedious".
![image](https://user-images.githubusercontent.com/4327356/57249618-0b6aa380-700b-11e9-9497-c4421542d2df.png)

**Comment by soamyak** [comment]
I am too facing the same issue, any update or resolution on this one ?

**Comment by lestrrat** [comment]
This is expected. Go cannot interrupt C-level processing. You will have to install a signal handler in the Go layer, and bail out yourself
