### ISSUE TITLE
Throws error while debugging

### ISSUE THREAD

**Issue by soamyak** [lestrrat-go/libxml2#58]
OK, So after many hurdles I got this library working in my windows and was able to host it in my docker too but the new challenge which I am facing is now :

1) I cannot debug my code. It gives some dependencies error -

github.com/lestrrat-go/libxml2/clib In file included from C:/msys64/usr/include/libxml2/libxml/parser.h:810:0, from C:/msys64/usr/include/libxml2/libxml/HTMLparser.h:16, from ....\github.com\lestrrat-go\libxml2\clib\clib.go:28: C:/msys64/usr/include/libxml2/libxml/encoding.h:28:19: fatal error: iconv.h: No such file or directory compilation terminated. exit status 2 Process exiting with code: 1

2) Ctrl plus C is not working to terminate the terminal session. It is very annoying.

**Comment by lestrrat** [comment]
1. Please read the error more carefully, and you will notice that the error has nothing to do with the Go layer, but in the C layer.

```
C:/msys64/usr/include/libxml2/libxml/encoding.h:28:19:
fatal error: iconv.h: No such file or directory compilation terminated. exit status 2 Process exiting with code: 1
```

2. I have no clue why you would consider Ctrl-C not working this library's fault when you can't even compile the C layer properly (i.e. what you are saying is that you can't even load the library, so why would it cause a runtime problem?)

Closing this issue for now.
