### ISSUE TITLE
the coding is error. 

### ISSUE THREAD

**Issue by 474420502** [lestrrat-go/libxml2#64]
coding is error!  the case is here.

test.html is in test.zip

[test.zip](https://github.com/lestrrat-go/libxml2/files/4918509/test.zip)

```golang
func TestCase(t *testing.T) {
	f, _ := os.Open("./test.html")
	data, _ := ioutil.ReadAll(f)

	doc, err := libxml2.ParseHTML(data)
	if err != nil {
		panic(err)
	}
	xr, err := doc.Find("//h1[ contains(@class, 'MovieTitle__Title')]")
	if err != nil {
		panic(nil)
	}
	t.Error(xr)
}
```

**Comment by lestrrat** [comment]
I don't understand. if you use `t.Error` at the end, then the title is displayed as an error. "coding is error" does not tell me anything. Please be more specific.

**Comment by lestrrat** [comment]
*If* you are talking about the mojibake, then you should explicitly state this.

```
% go test -run=GH64
--- FAIL: TestGH64 (0.01s)
    gh_test.go:23: ãsplatoon2ãã·ã£ã¼ããªãªã¼ã«ã¬ã³
                                                        
FAIL
exit status 1
FAIL	github.com/lestrrat-go/libxml2	0.579s
```

Now, if that was your problem, then it just means that the C libxml2 was not able to detect the encoding. Merely adding this to the beginning of your document fixes it:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
                      "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
    <title data-react-helmet="true">【splatoon2】シャープなリールガン | OPENREC.tv (オープンレック)</title>
```

Then I get

```
% go test -run=GH64  
--- FAIL: TestGH64 (0.00s)
    gh_test.go:23: 【splatoon2】シャープなリールガン
                                                        
FAIL
exit status 1
```

**Comment by 474420502** [comment]
thanks. @lestrrat 
t.Error() is only to show message.
is there any method to set   the encoding of libxml2?

**Comment by lestrrat** [comment]
You can set the encoding of the OUTPUT, but you cannot set the encoding of the input.

This is a _binding_ to libxml2, so you should read their documents: http://xmlsoft.org/encoding.html

On a more practical note, it's far easier to get the document, use something like `perl` to insert the proper html tags, and then run it through libxml than try to jump hoops with the encoding.

**Comment by 474420502** [comment]
thanks for your suggestions @lestrrat
I had solved the coding problem.
I am looking for a better solution to the problem.
