### ISSUE TITLE
[Feature Request] Populate Defaults from Schema

### ISSUE THREAD

**Issue by johnnybubonic** [lestrrat-go/libxml2#65]
XML Schema supports defaults in certain contexts. e.g.

```xml
<!-- ... -->
<xs:attribute name="someAttr" type="xs:string" default="this attribute was not specified" use="optional"/>
<!-- ... -->
```

With the above example, let's say we have a document:

```xml
<foo>
  <bar someAttr="this is populated"/>
  <bar/>
</foo>
```

This is possible with python [lxml](https://lxml.de/)'s `etree.XMLParser()` (which uses libxml2) (example [here](https://git.square-r00t.net/AIF-NG/tree/aif/config/parser.py?h=v2_rewrite#n105)). (source for lxml.etree is [here](https://github.com/lxml/lxml/blob/master/src/lxml/etree.pyx)).

I think it'd be a really handy thing to have.

~(Along similar lines, any ideas on how to strip namespaces from documents? I can do it with lxml [like this](https://git.square-r00t.net/AIF-NG/tree/aif/config/parser.py?h=v2_rewrite#n128) but I wasn't sure what struct fields there are in each element and whether the tag was able to be changed on the object or not. I'm still *really* new to golang and non-OOP, so my apologies if there's an obvious way to find this out.~ WHOA, I'm a dummy. Looks like it automatically separates out "Space" vs. "Local", at least when I unmarshal and marshal to JSON. That's pretty cool.

**Comment by lestrrat** [comment]
From what I can decipher via searches, the ability to insert default values in DOM using libxml2 comes when you validate a valid document using the schema -- that is, there is no "populateDefaults()" method in libxml2. So I tried to be true to the original API, and in #66 you should be able to do this

```go
schema, _ := xsd.Parse(...)
doc, _ := libxml2.Parse(...)

if err := schema.Validate(doc, xsd.ValueVCCreate); err != nil {
   ...
}
// now doc should have defaults provided
```

Can you try and see if it works for you?

**Comment by johnnybubonic** [comment]
I'd like to, but I can't seem to figure out how to use it. Apologies, I'm *really* new to golang.

```$ go get github.com/lestrrat-go/libxml2/xsd@topic/gh-issue-65
go get github.com/lestrrat-go/libxml2/xsd@topic/gh-issue-65: github.com/lestrrat-go/libxml2/xsd@topic/gh-issue-65: invalid version: version "topic/gh-issue-65" invalid: disallowed version string```

Is there a way I can just manually patch it via e.g https://github.com/lestrrat-go/libxml2/pull/66.patch and have golang rebuild the modcache or whatever else it needs to do, etc.?

**Comment by lestrrat** [comment]
Cool! Thanks for checking
