### ISSUE TITLE
Relative includes and HTTP(S) includes

### ISSUE THREAD

**Issue by johnnybubonic** [lestrrat-go/libxml2#67]
Similar to #50, I also use imports in my shcema ("`include`"s).

However, I use relative imports (where the "root" schema may be at `/foo/bar/baz.xsd`, and may include `/foo/bar/baz2.xsd` via `<xsi:include schemaLocation="./bar2.xsd"/>`, `/foo/quux/bar.xsd` via `<xsi:include schemaLocation="../quux/bar.xsd"/>`, etc.).

it seems that relative includes are not supported currently. Typically this is done in other language library implementations via a [baseURI](https://www.w3schools.com/xml/prop_node_baseuri.asp).

I propose that if we can specify a baseURI, relative includes would then be possible by resolving the baseURI + relative path = absolute path. Note also that this would allow for improved handling of recursive includes (as each included instance would then have its own baseURI as well).

Along those lines, parsing from an HTTP URL would be recommended and desired as well, as libxml2's `xmllint` does handle both remote URIs (HTTP only, not HTTPS) and local URIs, with relative includes:

```bash
$ xmllint -noout -schema http://schema.xml.r00t2.io/projects/aif.xsd aif.xml 
aif.xml validates
$ grep schemaLocation aif.xml 
     xsi:schemaLocation="https://aif-ng.io/ http://schema.xml.r00t2.io/projects/aif.xsd"
$ curl -sL "http://schema.xml.r00t2.io/projects/aif.xsd" | grep 'xs:include'
    <xs:include schemaLocation="../lib/types/aif.xsd"/>
$ curl -sL "http://schema.xml.r00t2.io/lib/types/aif.xsd" | grep 'xs:include'
    <xs:include schemaLocation="./gpg.xsd"/>
    <!-- <xs:include schemaLocation="./linux.xsd"/> --><!-- Included by the linux elements XSD. -->
    <xs:include schemaLocation="./net.xsd"/>
    <xs:include schemaLocation="./std.xsd"/>
    <xs:include schemaLocation="./unix.xsd"/>
    <xs:include schemaLocation="../elements/linux.xsd"/>
# (etc.)
```

**Comment by lestrrat** [comment]
In general no objections. If you could whip up a failing test as a PR, that would speed things up for me.

**Comment by johnnybubonic** [comment]
Awesome. Absolutely, give me a few!

**Comment by johnnybubonic** [comment]
PR supplied. Presumably, it'd need a new function `xsd.ParseFromHttp(uri string) (*Schema, error)` and a recursive function to handle nested `include` directives if the C library doesn't afford API methods for that. I know that it does [allow for setting the Base URI](http://www.xmlsoft.org/html/libxml-tree.html#xmlNodeSetBase) (of a document/node, at least).

I wish I could be of more help than that; my apologies. I know that the [python `lxml` module](https://github.com/lxml/lxml/tree/master/src/lxml) (see `etree.pyx` and `xmlschema.pxi`) has nested includes support, and http references work simply by providing the bytes of a schema and setting the base URI, but I'd have no idea how to implement it in golang.

Do not hesitate to ask me for any further sample data if it would help. Thank you!

**Comment by lestrrat** [comment]
#69 is the first cut at solving this issue https://github.com/lestrrat-go/libxml2/pull/69

Basically, you can now do

```
xsd.Parse(byteArray, xsd.WithURI("http://foo/bar/data.xsd"))
```

to resolve relative paths.

Now, this works, but I have a feeling that (1) it needs to be mirrored in the regular `libxml2.Parse` method. Still pondering about that part, and (2) There should be a libxml2.ParseURI, and xsd.ParseURI.

Anyway, for now please see if #69 works for you

**Comment by lestrrat** [comment]
@johnnybubonic apparently I forgot to mention you by name. so ping

**Comment by johnnybubonic** [comment]
whoops, sorry! i saw this come in but it slipped my mind. i'll test and let you know within a couple hours; thanks!

**Comment by johnnybubonic** [comment]
sorry for the delay in this. confirmed, works great!
