### ISSUE TITLE
invalid selfClosing Tag 

### ISSUE THREAD

**Issue by FanHuaRan** [lestrrat-go/libxml2#73]
code:
![image](https://user-images.githubusercontent.com/18598332/102315270-d4ae8a80-3fae-11eb-8e2c-137bd1394dfb.png)

output：
![image](https://user-images.githubusercontent.com/18598332/102315313-e4c66a00-3fae-11eb-9a63-9a163e7a199c.png)

but 'a' is not valid selfClosing tag in html.
 How avoid SelfClosing tag?

**Comment by lestrrat** [comment]
@FanHuaRan I'm sorry, but I don't use the HTML parser much, so I don't know.

Also this library is a *_binding_* to [libxml2](http://xmlsoft.org/). This library does not do anything more than what [libxml2](http://xmlsoft.org/) can do. Please read their manual, and ask questions on libxml2 usage elsewhere. If you find that you can't do something that the original libxml2 can do, but this library can't (or is doing wrong), then please let us know
