### ISSUE TITLE
ERROR pkg-config --cflags  -- libxml-2.0

### ISSUE THREAD

**Issue by asyncins** [lestrrat-go/libxml2#75]
When execute `go run main.do`，console show this:
```
# pkg-config --cflags  -- libxml-2.0
pkg-config: exec: "pkg-config": executable file not found in $PATH
```

------
1. MacOS Catalina 10.15.7;
2. Alredy installed `libxml2`, use `brew install libxml2`;
3. Other golang program can be run, business as usual;

What should I do?

**Comment by lestrrat** [comment]
Hi, please read the [FAQ](https://github.com/lestrrat-go/libxml2#faq). 

> If you are installing via some sort of package manager like apt/apk, remember that you need to install the "development" files as well. The name of the package differs in each environment, but it's usually something like "libxml2-dev".

>If you don't understand what pkg-config does, this is where you should either look for your local sysadmin friend, or study how these things work before filing an issue on this repository.

**Comment by asyncins** [comment]
It's done，thank you @lestrrat

**Comment by asyncins** [comment]
> It's done，thank you @lestrrat

When execute `pkg-config --list-all`,console show this:
```
command not found: pkg-config
```

Got it! should execute `brew install pkg-config`, wait installation completed, execute `pkg-config --list-all`:
```
libecpg_compat libecpg_compat - PostgreSQL libecpg_compat library
libxslt        libxslt - XSLT library version 2.
zlib           zlib - zlib compression library
libxml-2.0     libXML - libXML library version2.
...
...
```

Now, program can be run. Thand you @lestrrat

**Comment by lestrrat** [comment]
Cool!
