### ISSUE TITLE
Support for RelaxNG schemas

### ISSUE THREAD

**Issue by dmnyu** [lestrrat-go/libxml2#81]
Add support for parsing and validating RelaxNG schemas from the libxml2 relaxng module

**Comment by dmnyu** [comment]
I have this working in a branch, still needs a few tweaks, if this is functionality you'd want added to your library.

**Comment by lestrrat** [comment]
Sure, that would be nice

**Comment by fbaube** [comment]
DTDs would be great too. They might seem obsolete, but they are straightforward to read and understand.
