### ISSUE TITLE
Cross-compiling from linux to windows

### ISSUE THREAD

**Issue by hans-m-song** [lestrrat-go/libxml2#83]
I seem to be having some issues cross-compiling from linux to windows.

Here is a reproducible example:

`Dockerfile`

```Dockerfile
FROM --platform=linux/amd64 ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install -y \
  ca-certificates \
  curl \
  gcc-mingw-w64 \
  libc6 \
  libc6-dev \
  libxml2 \
  libxml2-dev \
  pkg-config

RUN curl -Lf "https://go.dev/dl/go1.18.3.linux-amd64.tar.gz" -o "go.tar.gz" \
  && tar -C /usr/local -xzf go.tar.gz \
  && rm -f go.tar.gz \
  && mkdir -p /home/test
ENV PATH=/usr/local/go/bin:$PATH

WORKDIR /home/test
COPY go.mod main.go ./
RUN go mod tidy

ENV GOOS=windows
ENV CC=x86_64-w64-mingw32-gcc
ENV CGO_ENABLED=1
ENV GOARCH=amd64
ENV CGO_CFLAGS=-I/usr/include

# this fails!
RUN go build
```

`go.mod`

```
module test

go 1.18

require (
	github.com/lestrrat/go-libxml2 v0.0.0-20180221004755-bb78334e2019
)
```

`main.go`

```go
package main

import (
	"github.com/lestrrat/go-libxml2/xsd"
)

func main() {
	xsd.ParseFromFile("")
}
```

Attempting to build the image results in the following error:

```
# github.com/lestrrat/go-libxml2/clib
In file included from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/HTMLparser.h:16,
                 from /root/go/pkg/mod/github.com/lestrrat/go-libxml2@v0.0.0-20180221004755-bb78334e2019/clib/clib.go:28:
/usr/include/libxml2/libxml/encoding.h:28:10: fatal error: iconv.h: No such file or directory
   28 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.
```

Using `CGO_FLAGS=-I/usr/include` doesn't seem to help either.

I can see the file `/usr/include/iconv.h` exists if built omitting the failing step in the dockerfile and `pkg-config` recognises `libxml2`.

```
# pkg-config --list-all
shared-mime-info shared-mime-info - Freedesktop common MIME database
libxcrypt        libxcrypt - Extended crypt library for DES, MD5, Blowfish and others
icu-uc           icu-uc - International Components for Unicode: Common and Data libraries
icu-i18n         icu-i18n - International Components for Unicode: Internationalization library
libxml-2.0       libXML - libXML library version2.
libcrypt         libxcrypt - Extended crypt library for DES, MD5, Blowfish and others
icu-io           icu-io - International Components for Unicode: Stream and I/O Library
```

Sorry if this is the wrong place to put this, I figure this is more to do with `cgo` than `libxml2` but I'm at a loss as to how to proceed. Probably similar to https://github.com/lestrrat-go/libxml2/issues/80 (I have encountered their issue as well).

**Comment by lestrrat** [comment]
I'm not much of an expert around this, but one thing I suspect is that libxml2 was not installed with `/usr/include` ? 

What does `pkg-config --libs libxml2` tell you?

**Comment by hans-m-song** [comment]
Here is the output:

```
# pkg-config --libs libxml2
Package libxml2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml2' found
```

I take it you are expecting `libxml2` instead of `libxml-2.0`?

**Comment by lestrrat** [comment]
Oh, now that I think about it, did you install `libxml2-dev` or `libxml2-devel` or whatever it is?

**Comment by hans-m-song** [comment]
Yes I have, if you have a look at the `Dockerfile`, I have installed

- `pkg-config`
- `gcc-mingw-w64` for cross-compilation
- `libc6`, `libc6-dev` which I believe contains `libiconv`
- `libxml2`, `libxml2-dev`

**Comment by lestrrat** [comment]
Oh, hmm... sorry now I'm stumped.  :/

**Comment by hans-m-song** [comment]
No worries, I figured it's not really an issue with your package (which I have found quite useful, thanks for that!). I will keep digging. Feel free to close this.
