### ISSUE TITLE
parser error : internal error: Huge input lookup

### ISSUE THREAD

**Issue by pengdengke** [lestrrat-go/libxml2#86]
Hello, I have some problems in use. I don't know why. Do you have time to analyze and answer them for me?
```golang
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/lestrrat/go-libxml2"
)

func main() {
	xmlbytes, err := ioutil.ReadFile("MyXML.xml")
	if err != nil {
		fmt.Println("111111111111", err)
		return
	}
	_, err = libxml2.ParseString(string(xmlbytes))
	if err != nil {
		fmt.Println("2222222", err)
		return
	}
}
```
The MyXML.xml details are as follows:
```shell
[root@localhost ~]# ll MyXML.xml
---------- 1 root root 28678359 Aug 14 18:56 MyXML.xml
```
Program run results:
```text
Entity: line 2: parser error : internal error: Huge input lookup
GJGJGJGJGJGJGJGJGJGJGJGJGJGJGJErp5JJRKJRKJRKJRKJRKJRKJRKJRJKJRKJRKJRJJP/AOBr/9k=
                                                                               ^
2222222 failed to create parse input: parse failed
```

I was thinking, is it because my xml file is too large or do I need to upgrade the library

**Comment by lestrrat** [comment]
Any time you see that sort of error, it's in libxml2, the underlying C library, so there's absolutely nothing I can do for you code-wise.

In this case though, the error should be obvious: your input is too large (that's what the error says :)
Your immediate response should be to google with the error message, and you should find posts about passing some flags, i.e. XML_PARSE_HUGE, which translates to libxml2.XMLParseHuge in this wrapper.

Please do not ask me if it should fix your problems, though, I personally have never used that option, so will not be able to help you there. If you find that the option works in raw libxml2 but not in this library, then it's my problem, so do let me know.
