### ISSUE TITLE
RemoveChild() for AttributeNode

### ISSUE THREAD

**Issue by jgpawletko** [lestrrat-go/libxml2#87]
Thank you, @lestrrat, for such a useful package!

I was wondering if there is a technical reason that the `RemoveChild()` function returns immediately when an `AttributeNode` is detected:
https://github.com/lestrrat-go/libxml2/blob/e6d9de61b80d0c4c527d9a014dfdf9744d706232/clib/clib.go#L1176-L1179

If not, I may work on a PR to add this functionality as I have a use case that would benefit from this feature, (and it would be a great learning opportunity 😃).

Thank you again!

**Comment by lestrrat** [comment]
I honestly don't remember why off the top of my head, but I'd venture to guess that attributes/namespaces are  stored as linked lists off of an element node, and therefore do not work with RemoveChild semantics

**Comment by jgpawletko** [comment]
Thank you for your quick reply, @lestrrat!
I will poke around to see if I can work up an implementation, tests, and PR.
Cheers!

**Comment by jgpawletko** [comment]
I was able to solve this using `Element.RemoveAttribute()`.
Apologies for the noise.
